Fix type stub for MainClass.get_user
-   Add `login` arg default value to stub to match source

#### example
```python3
from github import Github

Github("").get_user()
```

#### mypy before
```console
% mypy example.py
example.py:3: error: All overload variants of "get_user" of "Github" 
require at least one argument
example.py:3: note: Possible overload variants:
example.py:3: note:     def get_user(self, login: _NotSetType) -> 
AuthenticatedUser
example.py:3: note:     def get_user(self, login: str) -> NamedUser
Found 1 error in 1 file (checked 1 source file)
```

#### mypy after
```console
% mypy example.py
Success: no issues found in 1 source file
```